import type { Agent, Property } from "./types";

export const sampleAgents: Agent[] = [
  { id: "sofia", name: "Sofia Monteiro", role: "Sócia e Gerente", phone: "+351 233 408 130", email: "geral.figueirahome@gmail.com", photo_url: null },
  { id: "miguel", name: "Miguel Germano", role: "Diretor Comercial", phone: "+351 913 702 002", email: "geral.figueirahome@gmail.com", photo_url: null },
  { id: "maria", name: "Maria José Boia", role: "Consultora", phone: "+351 233 408 130", email: "geral.figueirahome@gmail.com", photo_url: null },
  { id: "alexandra", name: "Alexandra Santos", role: "Consultora", phone: "+351 233 408 130", email: "geral.figueirahome@gmail.com", photo_url: null }
];

export const sampleProperties: Property[] = [
  {
    id: "p1",
    slug: "apartamento-t2-terraco-piscina-buarcos",
    title: "Terraço com piscina panorâmica e vista mar",
    description: "Apartamento T2 em Buarcos com terraço, piscina panorâmica e vista sobre o mar. Uma opção preparada para quem procura proximidade à praia e conforto no dia a dia.",
    business: "comprar",
    type: "Apartamento T2",
    location: "Figueira da Foz - Buarcos",
    price: 420000,
    bedrooms: 2,
    bathrooms: 2,
    area_sqm: 120,
    status: "Em Destaque",
    featured: true,
    published: true,
    agent_id: "miguel",
    created_at: "2026-05-22T10:00:00Z",
    updated_at: "2026-05-22T10:00:00Z",
    agent: sampleAgents[1],
    images: [{ url: "", alt: "Vista mar em Buarcos", sort_order: 1, is_primary: true }]
  },
  {
    id: "p2",
    slug: "moradia-t3-quiaios-conforto",
    title: "Tranquilidade e conforto em Quiaios",
    description: "Moradia T3+1 em Quiaios, com áreas equilibradas, três casas de banho e envolvente tranquila. Indicada para residência permanente ou casa de férias.",
    business: "comprar",
    type: "Moradia T3+1",
    location: "Quiaios - Figueira da Foz",
    price: 299000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqm: 137,
    status: "Moradia",
    featured: true,
    published: true,
    agent_id: "maria",
    created_at: "2026-05-10T10:00:00Z",
    updated_at: "2026-05-10T10:00:00Z",
    agent: sampleAgents[2],
    images: [{ url: "", alt: "Moradia em Quiaios", sort_order: 1, is_primary: true }]
  },
  {
    id: "p3",
    slug: "moradia-t7-luxo-vista-mar-serra",
    title: "O Refúgio Perfeito - Vista sobre mar e serra",
    description: "Moradia T7 de luxo na Figueira da Foz com vista ampla sobre mar e serra, pensada para famílias que valorizam privacidade, espaço e localização.",
    business: "comprar",
    type: "Moradia T7 de Luxo",
    location: "Figueira da Foz",
    price: 1200000,
    bedrooms: 7,
    bathrooms: 5,
    area_sqm: 325,
    status: "Vista Mar",
    featured: true,
    published: true,
    agent_id: "sofia",
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-18T10:00:00Z",
    agent: sampleAgents[0],
    images: [{ url: "", alt: "Moradia com vista mar e serra", sort_order: 1, is_primary: true }]
  },
  {
    id: "p4",
    slug: "apartamento-t2-buarcos-ate-300-mil",
    title: "Apartamento T2 em Buarcos perto da marginal",
    description: "Apartamento T2 em Buarcos com boa exposição solar e acesso rápido a serviços, praia e marginal.",
    business: "comprar",
    type: "Apartamento T2",
    location: "Buarcos",
    price: 285000,
    bedrooms: 2,
    bathrooms: 1,
    area_sqm: 92,
    status: "Disponível",
    featured: false,
    published: true,
    agent_id: "alexandra",
    created_at: "2026-06-01T10:00:00Z",
    updated_at: "2026-06-01T10:00:00Z",
    agent: sampleAgents[3],
    images: [{ url: "", alt: "Apartamento T2 em Buarcos", sort_order: 1, is_primary: true }]
  }
];
