import type { Metadata } from "next";
import Link from "next/link";
import { VideoFooter } from "@/components/video-footer";

export const metadata: Metadata = { title: "Política de Cookies", description: "Política de cookies da Figueira Home." };

export default function CookiesPage() {
  return <><main className="legal-page bg-[var(--offwhite)] pt-28"><article className="container max-w-4xl py-14 md:py-20"><Link href="/" className="text-sm font-bold text-[var(--blue)]">← Voltar ao início</Link><p className="eyebrow mt-10">Figueira Home</p><h1 className="section-title mt-4">Política de Cookies</h1><p className="mt-4 text-sm text-[var(--muted)]">Última atualização: 28 de agosto de 2026</p><div className="privacy-prose mt-12">
    <section><h2>1. O que são cookies?</h2><p>Cookies são pequenos ficheiros de informação armazenados no seu equipamento através do navegador. Retêm informação relacionada com as suas preferências e com o funcionamento do website, não incluindo, por si só, dados pessoais que o identifiquem diretamente.</p></section>
    <section><h2>2. Para que servem?</h2><p>Os cookies ajudam a tornar a navegação mais rápida, segura e eficiente, permitindo recordar opções técnicas e compreender o funcionamento do website. Podem também ser usados, quando consentidos, para análise de utilização ou para melhorar os serviços disponibilizados.</p></section>
    <section><h2>3. Tipos e duração</h2><p>Os cookies de sessão são temporários e são apagados quando fecha o navegador. Os cookies persistentes permanecem no equipamento até serem apagados ou até ao respetivo prazo de expiração, permitindo recordar preferências numa visita futura.</p></section>
    <section><h2>4. Categorias de cookies</h2><p><strong>Estritamente necessários:</strong> permitem a navegação, a segurança e a utilização das funcionalidades essenciais do website. Sem estes cookies, alguns serviços solicitados não podem ser disponibilizados.</p><p><strong>Funcionalidade:</strong> guardam preferências de utilização, para que não seja necessário configurar novamente o website em cada visita.</p><p><strong>Analíticos:</strong> permitem recolher estatísticas agregadas sobre a utilização do website, para melhorar o seu funcionamento.</p><p><strong>De terceiros e publicidade:</strong> podem medir a eficácia de aplicações, conteúdos ou publicidade de terceiros e personalizar comunicações. Estes só serão utilizados quando aplicável e com o consentimento exigido por lei.</p></section>
    <section><h2>5. Cookies utilizados neste website</h2><p>O website utiliza cookies estritamente necessários ao seu funcionamento e à prestação dos serviços disponibilizados, incluindo o do seletor de idioma (Google Translate).</p><p>Utilizamos ainda, apenas após o seu consentimento prévio dado no banner de cookies, o <strong>Google Analytics</strong> (estatísticas agregadas de utilização do website) e o <strong>Meta Pixel</strong> (medição da eficácia de campanhas de publicidade no Facebook e Instagram). Estes cookies só são instalados depois de aceitar essa opção, e pode retirar o consentimento a qualquer momento em "Preferências de Cookies", no rodapé do website.</p></section>
    <section><h2>6. Gestão das preferências</h2><p>Pode alterar, bloquear ou eliminar cookies nas definições do seu navegador. A desativação de cookies necessários pode afetar algumas funcionalidades do website. Para informação independente sobre gestão de cookies, consulte <a href="https://www.allaboutcookies.org/" target="_blank" rel="noreferrer">allaboutcookies.org</a>.</p></section>
    <section><h2>7. Processamento e transferências</h2><p>As informações recolhidas podem ser tratadas pela Figueira Home ou por prestadores de serviços necessários ao funcionamento do website. Caso exista transferência de informação para fora do Espaço Económico Europeu, serão aplicadas as garantias legalmente exigidas para assegurar a proteção dos dados.</p></section>
    <section><h2>8. Alterações a esta política</h2><p>A Figueira Home pode atualizar esta Política de Cookies a qualquer momento. A versão em vigor será sempre a que se encontra publicada nesta página. Para informação sobre o tratamento de dados pessoais, consulte a <Link href="/politica-privacidade">Política de Privacidade</Link>.</p></section>
  </div></article></main><VideoFooter /></>;
}
