import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, ChartNoAxesCombined, GraduationCap, Handshake, Sparkles, UsersRound } from "lucide-react";
import { RecruitmentForm } from "@/components/recruitment-form";
import { VideoFooter } from "@/components/video-footer";

export const metadata: Metadata = { title: "Recrutamento", description: "Construa uma carreira no imobiliário com acompanhamento, formação e tecnologia na Figueira Home." };

const benefits: Array<[typeof UsersRound, string, string]> = [
  [UsersRound, "Acompanhamento próximo", "Orientação direta nos primeiros passos e apoio em cada fase."],
  [BadgeCheck, "Método para começar", "Formação prática, processos claros e objetivos acompanhados."],
  [Sparkles, "Tecnologia e IA", "Ferramentas atuais de comunicação, organização e apresentação ao serviço do seu trabalho."],
  [ChartNoAxesCombined, "Crescimento com direção", "Um contexto exigente, com espaço para construir resultados consistentes."],
];

const modules = ["Fundamentos Figueira Home", "Ferramentas e tecnologia", "Geração de atenção", "Prospecção e canais de aquisição", "Qualificação do vendedor", "Reunião em casa do proprietário", "Angariação", "Promoção do imóvel", "Gestão de compradores", "Negociação e fecho", "Pós-venda e fidelização"];
const academyTopics = ["Leads mortas: oportunidades mal trabalhadas", "Consultores desorganizados, negócios perdidos", "CPCV: método que transforma ética em resultados", "Legal no imobiliário: ética e enquadramento", "Integridade e comissão", "PNL na angariação", "Inteligência artificial no imobiliário", "Nova era do CRM", "Sustentabilidade no negócio", "Gestão de risco e resultados", "LinkedIn com IA para gerar clientes", "Comunicação profissional no imobiliário"];
const faqs = [["Preciso de experiência no imobiliário?", "Não. Valorizamos sobretudo ambição, capacidade de aprendizagem, iniciativa e compromisso. A formação e o acompanhamento fazem parte da integração."], ["Vou ter formação?", "Sim. Começa com uma base prática de integração e tem acesso a formação contínua, aplicada aos desafios do mercado."], ["Esta oportunidade é para toda a gente?", "Não. É indicada para quem quer assumir uma carreira com autonomia, objetivos e vontade de evoluir."], ["Vou estar sozinho no início?", "Não. O objetivo é que comece acompanhado, com método, ferramentas e uma equipa disponível."], ["Tenho de decidir já?", "Não. A primeira conversa serve para conhecer a oportunidade e perceber se existe alinhamento dos dois lados."]];

export default function RecruitmentPage() {
  const jobPosting = { "@context": "https://schema.org", "@type": "JobPosting", title: "Consultor(a) Imobiliário(a)", description: "Oportunidade de carreira no imobiliário com acompanhamento, formação e tecnologia.", datePosted: "2026-07-14", employmentType: "FULL_TIME", hiringOrganization: { "@type": "Organization", name: "Figueira Home" }, jobLocation: { "@type": "Place", address: { "@type": "PostalAddress", addressLocality: "Figueira da Foz", addressCountry: "PT" } } };
  return <><main>
    <section className="recruitment-hero relative isolate overflow-hidden bg-[var(--navy)] pt-[72px] text-white"><div className="recruitment-hero-mark" /><div className="container relative z-10 grid min-h-[610px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="mb-5 text-xs font-extrabold uppercase tracking-[0.22em] text-[var(--gold-l)]">Recrutamento · Figueira da Foz</p><h1 className="display-font max-w-3xl text-[clamp(3rem,6vw,5.7rem)] font-extrabold leading-[0.9]">O imobiliário pode transformar a sua vida.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/78">Mesmo sem experiência no imobiliário, encontra uma equipa com método, acompanhamento e ferramentas para transformar ambição em ação.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#perfil" className="btn btn-gold">Perceber se tenho perfil <ArrowRight size={17} /></Link><Link href="#processo" className="btn btn-outline-light">Como funciona</Link></div></div><aside className="recruitment-hero-card"><BriefcaseBusiness size={30} /><p>Consultor(a) Imobiliário(a)</p><strong>Não precisa de chegar com todas as respostas.</strong><span>Precisa de querer aprender, construir relações e crescer com uma equipa presente.</span></aside></div></section>

    <section className="container py-20 md:py-28"><div className="grid gap-12 md:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Esta oportunidade pode ser para si se...</p><h2 className="section-title mt-4">Procura mais direção para a sua carreira.</h2></div><p className="max-w-2xl text-[1.05rem] leading-8 text-[var(--muted)]">Talvez esteja insatisfeito com o trabalho atual, queira mudar de carreira, ganhar mais, valorize autonomia ou simplesmente tenha ambição sem experiência no setor. A maioria das pessoas não fica parada por falta de capacidade; fica parada por falta de direção.</p></div><div className="recruitment-fit-grid mt-14">{["Está insatisfeito com o trabalho atual", "Quer mudar de carreira", "Quer ganhar mais", "Valoriza autonomia", "Ainda não tem experiência, mas tem ambição"].map((item, index) => <p key={item}><b>0{index + 1}</b>{item}</p>)}</div></section>

    <section className="bg-[var(--offwhite)] py-20 md:py-28"><div className="container"><div className="grid gap-12 md:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Método e acompanhamento</p><h2 className="section-title mt-4">Aqui não entra para ficar perdido. Entra para ser acompanhado.</h2></div><p className="max-w-2xl text-[1.05rem] leading-8 text-[var(--muted)]">A integração combina liderança experiente, formação contínua, tecnologia e espaço para crescer. O objetivo é que avance com clareza, prática e apoio quando precisa.</p></div><div className="mt-14 grid gap-px overflow-hidden border border-[var(--border)] bg-[var(--border)] sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon, title, description]) => <article key={title} className="bg-white p-7"><Icon className="text-[var(--blue)]" size={25} /><h3 className="mt-6 font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{description}</p></article>)}</div></div></section>

    <section className="container py-20 md:py-28"><div className="recruitment-section-head"><div><p className="eyebrow">Formação de alto nível</p><h2 className="section-title mt-4">Do zero ao primeiro negócio, com um percurso concreto.</h2></div><p>O programa de integração cobre as etapas centrais do trabalho imobiliário. A academia complementa esse percurso com conteúdos aplicados ao mercado real.</p></div><div className="recruitment-learning mt-12"><div><GraduationCap size={28} /><p className="eyebrow">Integração Figueira Home</p><h3>11 módulos para começar com método.</h3><ol>{modules.map((module, index) => <li key={module}><b>{String(index).padStart(2, "0")}</b>{module}</li>)}</ol></div><div><Handshake size={28} /><p className="eyebrow">Academia Novo Imobiliário</p><h3>Conteúdos que preparam para o mercado real.</h3><ol>{academyTopics.map((topic, index) => <li key={topic}><b>{String(index + 1).padStart(2, "0")}</b>{topic}</li>)}</ol></div></div></section>

    <section className="recruitment-method bg-[var(--navy)] py-20 text-white md:py-28"><div className="container"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[var(--gold-l)]">O que encontra connosco</p><h2 className="display-font mt-4 text-4xl font-extrabold">Não é sorte. É método, acompanhamento e ferramentas certas.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{["Começar sem se sentir perdido", "Ganhar confiança mais rápido", "Aprender com método", "Usar ferramentas atuais", "Ter uma cultura de crescimento", "Construir uma carreira com potencial"].map((item, index) => <div key={item}><b>0{index + 1}</b><span>{item}</span></div>)}</div></div></section>

    <section className="container py-20 md:py-28"><div className="recruitment-section-head"><div><p className="eyebrow">Modelo de progressão</p><h2 className="section-title mt-4">Quanto mais produz, mais recebe.</h2></div><p>O potencial cresce com resultados, método e compromisso. Estes são os patamares apresentados na oportunidade.</p></div><div className="mt-12 overflow-x-auto border border-[var(--border)]"><table className="recruitment-table"><thead><tr><th>Patamar</th><th>Faturação bruta / ano</th><th>Fee mensal</th><th>Fee por CMI</th></tr></thead><tbody>{[["40%", "até € 50 000", "—", "—"], ["50%", "€ 50 001 – € 70 000", "—", "—"], ["60%", "€ 70 001 – € 80 000", "€100/mês", "€100/CMI"], ["70%", "€ 80 001 – € 100 000", "€200/mês", "€200/CMI"], ["80%", "acima de € 100 000", "€300/mês", "€300/CMI"]].map(row => <tr key={row[0]}>{row.map(cell => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">Os detalhes do modelo e o respetivo enquadramento são explicados na primeira conversa.</p></section>

    <section id="perfil" className="bg-[var(--offwhite)] py-20 md:py-28"><div className="container"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">O primeiro passo</p><h2 className="section-title mt-4">Tens perfil para construir uma carreira no imobiliário?</h2><p className="mt-5 leading-8 text-[var(--muted)]">São 10 perguntas breves sobre a forma como trabalha, aprende e se relaciona. No final, pode enviar a candidatura completa.</p></div><RecruitmentForm /></div></section>

    <section id="processo" className="container py-20 md:py-28"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Candidatura</p><h2 className="section-title mt-4">Como funciona o processo.</h2></div><ol className="recruitment-process mt-14">{[["01", "Preenche o formulário", "Partilha o seu contexto e o que procura numa nova fase."], ["02", "Falamos consigo", "Entramos em contacto pelo canal que indicou."], ["03", "Apresentamos a oportunidade", "Explicamos o modelo, a equipa e o percurso de integração."], ["04", "Decidimos o próximo passo", "Percebemos em conjunto se existe o alinhamento certo."]].map(([number, title, text]) => <li key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p></li>)}</ol></section>

    <section className="bg-[var(--offwhite)] py-20 md:py-28"><div className="container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Dúvidas frequentes</p><h2 className="section-title mt-4">Talvez esteja a pensar...</h2><p className="mt-5 leading-8 text-[var(--muted)]">Não tem de decidir já. Esta conversa existe para perceber se a oportunidade faz sentido para si.</p></div><div className="recruitment-faq">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>

    <section className="bg-[var(--navy)] py-16 text-white"><div className="container flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[var(--gold-l)]">Vamos conversar</p><h2 className="display-font mt-3 text-3xl font-extrabold">Talvez não precise de outro emprego. Talvez precise de uma nova direção.</h2></div><Link href="#perfil" className="btn btn-gold">Começar candidatura <ArrowRight size={17} /></Link></div></section>
  </main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jobPosting) }} /><VideoFooter variant="recruitment" /></>;
}
