import type { Metadata } from "next";
import Link from "next/link";
import { VideoFooter } from "@/components/video-footer";

export const metadata: Metadata = { title: "Política de Privacidade", description: "Política de privacidade da Figueira Home." };

export default function PrivacyPage() {
  return <><main className="legal-page bg-[var(--offwhite)] pt-28"><article className="container max-w-4xl py-14 md:py-20"><Link href="/" className="text-sm font-bold text-[var(--blue)]">← Voltar ao início</Link><p className="eyebrow mt-10">Figueira Home</p><h1 className="section-title mt-4">Política de Privacidade</h1><p className="mt-4 text-sm text-[var(--muted)]">Última atualização: 28 de agosto de 2026</p><div className="privacy-prose mt-12">
    <section><h2>1. Responsável pelo tratamento</h2><p>A Figueira Home, explorada por Ondaveloz – Mediação Imobiliária, Lda., com sede na Avenida do Brasil, 48, 3080-323 Buarcos, Figueira da Foz, NIPC 508322081 e licença AMI 7968, é responsável pelo tratamento dos dados pessoais recolhidos através deste website.</p><p>Para questões sobre privacidade ou exercício dos seus direitos, contacte-nos através de <a href="mailto:geral@figueirahome.pt">geral@figueirahome.pt</a>.</p></section>
    <section><h2>2. Objeto desta política</h2><p>Esta política explica como recolhemos, utilizamos, conservamos e protegemos os dados pessoais necessários para disponibilizar os serviços do website, nomeadamente pedidos de contacto e informação, candidaturas, subscrição de comunicações, gestão do website e melhoria dos nossos serviços.</p></section>
    <section><h2>3. Dados pessoais que podemos recolher</h2><p>Podemos recolher dados de identificação e contacto, como nome, email, telefone ou telemóvel, e dados fornecidos nos formulários, incluindo mensagens, preferência de contacto, localidade, situação profissional e informação relevante para uma candidatura.</p><p>Podemos ainda recolher dados técnicos associados à utilização do website, como endereço IP, navegador e dados de cookies, nos termos da Política de Cookies aplicável.</p></section>
    <section><h2>4. Finalidades e fundamentos do tratamento</h2><p>Tratamos os seus dados para responder a mensagens, pedidos de informação e apoio ao cliente; dar seguimento a candidaturas; enviar newsletters ou outras comunicações quando solicitado ou consentido; gerir e proteger o website; manter registos de contacto; realizar análises, auditorias e melhorias dos serviços; e prevenir fraudes ou incidentes de segurança.</p><p>O tratamento é realizado, conforme aplicável, com base no seu consentimento, na execução de diligências pré-contratuais solicitadas por si, no cumprimento de obrigações legais e nos interesses legítimos da Figueira Home, sempre com respeito pelo RGPD e pela legislação portuguesa aplicável.</p></section>
    <section><h2>5. Recolha através do website e cookies</h2><p>Os dados são recolhidos através dos formulários do website, comunicações por email e pela interação do seu equipamento com o website. Os cookies necessários ao funcionamento do website podem ser utilizados; os restantes dependem da sua aceitação, quando legalmente exigida.</p><p>Os serviços não se destinam a menores de 16 anos. Pedimos igualmente que não nos envie dados pessoais sensíveis, como dados de saúde, convicções religiosas ou opiniões políticas, através dos formulários ou email.</p></section>
    <section><h2>6. Conservação e segurança</h2><p>Conservamos os dados apenas durante o período necessário às finalidades para que foram recolhidos, à gestão da relação consigo ou ao cumprimento de obrigações legais. Adotamos medidas técnicas e organizativas adequadas para limitar o acesso, prevenir perda, alteração, divulgação ou tratamento não autorizado.</p></section>
    <section><h2>7. Destinatários e transferências</h2><p>Podemos recorrer a prestadores de serviços para alojamento, suporte técnico, gestão de dados e comunicações. No contexto deste website, os dados podem ser tratados através do Supabase para gestão interna e do MailerLite para comunicações às quais tenha aderido ou consentido. Estas entidades apenas recebem os dados necessários à prestação do serviço contratado e atuam sob garantias adequadas de proteção.</p><p>Não vendemos, alugamos ou cedemos os seus dados pessoais a terceiros para fins comerciais próprios. Poderemos comunicar dados quando tal for exigido por lei, autoridade competente ou decisão judicial. Quando ocorrerem transferências para fora do Espaço Económico Europeu, serão aplicadas as garantias legalmente exigidas.</p></section>
    <section><h2>8. Os seus direitos</h2><p>Pode solicitar acesso, retificação, apagamento, limitação do tratamento, oposição e portabilidade dos seus dados, bem como retirar o consentimento quando esse for o fundamento do tratamento. Para o efeito, contacte <a href="mailto:geral@figueirahome.pt">geral@figueirahome.pt</a>.</p><p>Tem ainda o direito de se opor ao processamento automatizado dos seus dados, incluindo a criação de perfis, e a não ficar sujeito a uma decisão baseada exclusivamente nesse processamento sempre que esta produza efeitos legais ou o afete significativamente. É o caso, por exemplo, do questionário de perfil da página de recrutamento: a pontuação obtida serve apenas para orientar um contacto humano posterior, nunca para decidir sozinha sobre uma candidatura.</p><p>Tem também o direito de apresentar reclamação junto da Comissão Nacional de Proteção de Dados, através de <a href="https://www.cnpd.pt/" target="_blank" rel="noreferrer">www.cnpd.pt</a>.</p></section>
    <section><h2>9. Contacto via WhatsApp</h2><p>Alguns canais do website (incluindo as páginas de imóveis, de consultores e de serviços) disponibilizam um botão de contacto direto via WhatsApp. Este canal é inteiramente opcional e independente dos restantes consentimentos prestados nos formulários do website.</p><p>Ao iniciar uma conversa por WhatsApp connosco, os dados tratados limitam-se ao número de telemóvel, nome e informação relacionada com o pedido imobiliário em causa (por exemplo, tipo de imóvel, localização ou orçamento). Estes dados são utilizados exclusivamente para dar seguimento a esse pedido — envio de informação sobre imóveis, esclarecimento de dúvidas, agendamento de visitas ou reuniões e acompanhamento do processo em curso — e não para publicidade genérica não relacionada com o mesmo.</p><p>A base legal deste tratamento é o consentimento explícito do titular dos dados (artigo 6.º, n.º 1, alínea a) do RGPD), dado ao iniciar voluntariamente o contacto através deste canal. As mensagens trocadas são conservadas apenas pelo tempo necessário para concluir o processo de mediação imobiliária em causa ou para cumprir obrigações legais aplicáveis à atividade de mediação.</p><p>Pode retirar este consentimento a qualquer momento, respondendo "PARAR" na conversa de WhatsApp, enviando um pedido para <a href="mailto:geral@figueirahome.pt">geral@figueirahome.pt</a> ou contactando-nos por telefone. Note que o WhatsApp é operado pela WhatsApp LLC (grupo Meta), pelo que a comunicação passa também pelos servidores dessa plataforma, nos termos da respetiva política de privacidade.</p></section>
    <section><h2>10. Websites de terceiros e alterações</h2><p>O website pode incluir ligações para websites de terceiros, cujas práticas de privacidade são da responsabilidade dos respetivos titulares. Poderemos atualizar esta política a qualquer momento; a versão em vigor será sempre a que estiver publicada nesta página.</p></section>
  </div></article></main><VideoFooter /></>;
}
